language: node_js

node_js:
  - "0.10"

install:
  - npm install mocha-browser component -g

test:
  - make test

after_success:
  - npm install jscoverage coveralls -g
  - make prepare-coverage
  - mocha-browser test/index.html -R lcov | coveralls
